import random

TRACKLIST = [
    {"artist": "The Weeknd", "title": "Blinding Lights"},
    {"artist": "Ed Sheeran", "title": "Shape of You"},
    {"artist": "Imagine Dragons", "title": "Perfect"},
    {"artist": "Harry Styles", "title": "As It Was"},
    {"artist": "Post Malone", "title": "Sunflower"},
    {"artist": "Dua Lipa", "title": "Levitating"},
    {"artist": "Billie Eilish", "title": "Don't Start Now"},
    {"artist": "Taylor Swift", "title": "Watermelon Sugar"},
    {"artist": "The Kid LAROI", "title": "Stay"},
    {"artist": "Olivia Rodrigo", "title": "Bad Guy"},
    {"artist": "Glass Animals", "title": "Believer"},
    {"artist": "Maroon 5", "title": "Someone You Loved"},
    {"artist": "Adele", "title": "Dance Monkey"},
    {"artist": "Shawn Mendes", "title": "Heat Waves"},
    {"artist": "Justin Bieber", "title": "Rockstar"},
    {"artist": "Coldplay", "title": "One Dance"},
    {"artist": "Bruno Mars", "title": "Closer"},
    {"artist": "Eminem", "title": "Uptown Funk"},
    {"artist": "Drake", "title": "Señorita"},
    {"artist": "Rihanna", "title": "Bad Habits"},
    {"artist": "Ariana Grande", "title": "Drivers License"},
    {"artist": "Katy Perry", "title": "Memories"},
    {"artist": "Lady Gaga", "title": "Despacito"},
    {"artist": "Sia", "title": "Thinking Out Loud"},
    {"artist": "Beyoncé", "title": "Lucid Dreams"},
    {"artist": "The Chainsmokers", "title": "Photograph"},
    {"artist": "Sam Smith", "title": "Starboy"},
    {"artist": "Charlie Puth", "title": "Say You Won't Let Go"},
    {"artist": "John Legend", "title": "Let Me Love You"},
    {"artist": "Hozier", "title": "Shallow"},
    {"artist": "Avicii", "title": "All of Me"},
    {"artist": "Calvin Harris", "title": "Take Me to Church"},
    {"artist": "David Guetta", "title": "Wake Me Up"},
    {"artist": "Marshmello", "title": "Roar"},
    {"artist": "Zedd", "title": "Radioactive"},
    {"artist": "Martin Garrix", "title": "Demons"},
    {"artist": "DJ Snake", "title": "Counting Stars"},
    {"artist": "Alan Walker", "title": "Thunder"},
    {"artist": "Kygo", "title": "Whatever It Takes"},
    {"artist": "Tiesto", "title": "Natural"},
    {"artist": "Alesso", "title": "Blank Space"},
    {"artist": "Afrojack", "title": "Havana"},
    {"artist": "Armin van Buuren", "title": "Cheap Thrills"},
    {"artist": "Hardwell", "title": "Love Yourself"},
    {"artist": "Skrillex", "title": "Treat You Better"},
    {"artist": "Steve Aoki", "title": "Just the Way You Are"},
    {"artist": "Deadmau5", "title": "I'm Yours"},
    {"artist": "Diplo", "title": "A Thousand Years"},
    {"artist": "Major Lazer", "title": "Stay With Me"},
    {"artist": "Flume", "title": "Let Her Go"},
    {"artist": "Odesza", "title": "Stitches"},
    {"artist": "Illenium", "title": "In My Blood"},
    {"artist": "Rufus Du Sol", "title": "There's Nothing Holdin' Me Back"},
    {"artist": "Disclosure", "title": "Mercy"},
    {"artist": "Porter Robinson", "title": "Attention"},
    {"artist": "Madeon", "title": "Too Good at Goodbyes"},
    {"artist": "San Holo", "title": "I Don't Care"},
    {"artist": "Petit Biscuit", "title": "Sorry"},
    {"artist": "Gryffin", "title": "What Do You Mean?"},
    {"artist": "Seven Lions", "title": "Peaches"},
    {"artist": "Said The Sky", "title": "Cold Water"},
    {"artist": "Dabin", "title": "We Don't Talk Anymore"},
    {"artist": "Slander", "title": "Let It Go"},
    {"artist": "Trivecta", "title": "Hold Back the River"},
    {"artist": "Jason Ross", "title": "Without Me"},
    {"artist": "Crystal Skies", "title": "Something Just Like This"},
    {"artist": "Nurko", "title": "Can't Stop the Feeling!"},
    {"artist": "William Black", "title": "Don't Let Me Down"},
    {"artist": "Mitis", "title": "Faded"},
    {"artist": "Far Out", "title": "Alone"},
    {"artist": "Gem & Tauri", "title": "Happier"},
    {"artist": "Au5", "title": "The Middle"},
    {"artist": "Fractal", "title": "Something Just Like This"},
    {"artist": "Xilent", "title": "Something Just Like This"},
    {"artist": "Chime", "title": "Let Me Love You"},
    {"artist": "Last Heroes", "title": "Let Me Love You"},
    {"artist": "Trivecta", "title": "Let Me Love You"},
    {"artist": "Wooli", "title": "Let Me Love You"},
    {"artist": "Kompany", "title": "Let Me Love You"},
    {"artist": "Ray Volpe", "title": "Let Me Love You"},
    {"artist": "PhaseOne", "title": "Let Me Love You"},
    {"artist": "Dirt Monkey", "title": "Let Me Love You"},
    {"artist": "Subtronics", "title": "Let Me Love You"},
    {"artist": "Excision", "title": "Let Me Love You"},
    {"artist": "Zeds Dead", "title": "Let Me Love You"},
    {"artist": "Ganja White Night", "title": "Let Me Love You"},
    {"artist": "Boogie T", "title": "Let Me Love You"},
    {"artist": "Liquid Stranger", "title": "Let Me Love You"},
    {"artist": "Peekaboo", "title": "Let Me Love You"},
    {"artist": "Svdden Death", "title": "Let Me Love You"},
    {"artist": "Rezz", "title": "Let Me Love You"},
    {"artist": "1788-L", "title": "Let Me Love You"},
    {"artist": "Blanke", "title": "Let Me Love You"},
    {"artist": "Ember", "title": "Let Me Love You"},
    {"artist": "Fairlane", "title": "Let Me Love You"},
    {"artist": "Ghost", "title": "Let Me Love You"},
    {"artist": "Inukshuk", "title": "Let Me Love You"},
    {"artist": "Skybreak", "title": "Let Me Love You"},
    {"artist": "Slippy", "title": "Let Me Love You"},
    {"artist": "Soltan", "title": "Let Me Love You"},
    {"artist": "Spag Heddy", "title": "Let Me Love You"},
    {"artist": "Squnto", "title": "Let Me Love You"},
    {"artist": "Trampa", "title": "Let Me Love You"},
    {"artist": "TrollPhace", "title": "Let Me Love You"},
    {"artist": "Tvboo", "title": "Let Me Love You"},
    {"artist": "Ubur", "title": "Let Me Love You"},
    {"artist": "Virtual Riot", "title": "Let Me Love You"},
    {"artist": "Yakz", "title": "Let Me Love You"},
    {"artist": "Yookie", "title": "Let Me Love You"},
    {"artist": "Zomboy", "title": "Let Me Love You"},
    {"artist": "Apashe", "title": "Let Me Love You"},
    {"artist": "Buku", "title": "Let Me Love You"},
    {"artist": "Bleep Bloop", "title": "Let Me Love You"},
    {"artist": "Champagne Drip", "title": "Let Me Love You"},
    {"artist": "Conrank", "title": "Let Me Love You"},
    {"artist": "Digital Ethos", "title": "Let Me Love You"},
    {"artist": "Eprom", "title": "Let Me Love You"},
    {"artist": "G Jones", "title": "Let Me Love You"},
    {"artist": "Herobust", "title": "Let Me Love You"},
    {"artist": "Luzcid", "title": "Let Me Love You"},
    {"artist": "Minnesota", "title": "Let Me Love You"},
    {"artist": "Space Jesus", "title": "Let Me Love You"},
    {"artist": "Truth", "title": "Let Me Love You"},
    {"artist": "Widdler", "title": "Let Me Love You"},
    {"artist": "Yheti", "title": "Let Me Love You"},
    {"artist": "Zeke Beats", "title": "Let Me Love You"},
    {"artist": "Ariana Grande", "title": "7 rings"},
    {"artist": "The Weeknd", "title": "Save Your Tears"},
    {"artist": "Lil Nas X", "title": "WITHOUT YOU"},
    {"artist": "Doja Cat", "title": "Kiss Me More"},
    {"artist": "Elton John", "title": "All of Me"},
    {"artist": "Ed Sheeran", "title": "Bad Habits"},
    {"artist": "Miley Cyrus", "title": "Flowers"},
    {"artist": "SZA", "title": "Kill Bill"},
    {"artist": "Billie Eilish", "title": "bad guy"},
    {"artist": "Post Malone", "title": "Circles"},
    {"artist": "Harry Styles", "title": "Watermelon Sugar"},
    {"artist": "Justin Bieber", "title": "Peaches"},
    {"artist": "Taylor Swift", "title": "Anti-Hero"},
    {"artist": "Dua Lipa", "title": "Don't Start Now"},
    {"artist": "Olivia Rodrigo", "title": "good 4 u"},
    {"artist": "The Kid LAROI", "title": "STAY"},
    {"artist": "Lil Nas X", "title": "MONTERO (Call Me By Your Name)"},
    {"artist": "Glass Animals", "title": "Heat Waves"},
    {"artist": "Shawn Mendes", "title": "Señorita"},
    {"artist": "Maroon 5", "title": "Girls Like You"},
    {"artist": "Ed Sheeran", "title": "Thinking out Loud"}
]

def get_random_track() -> dict:
    """Returns a random track from the 150-track list."""
    return random.choice(TRACKLIST)
